/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as AuthSetPasswordRouteImport } from './routes/auth/set-password'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as AuthMobileRouteRouteImport } from './routes/_auth/mobile/route'
import { Route as AuthSidebarLayoutRouteRouteImport } from './routes/_auth/_sidebarLayout/route'
import { Route as AuthAdminRouteRouteImport } from './routes/_auth/_admin/route'
import { Route as AuthMobileIndexRouteImport } from './routes/_auth/mobile/index'
import { Route as AuthSidebarLayoutIndexRouteImport } from './routes/_auth/_sidebarLayout/index'
import { Route as AuthProfileChangePasswordRouteImport } from './routes/_auth/profile/change-password'
import { Route as AuthMobileProfileRouteImport } from './routes/_auth/mobile/profile'
import { Route as AuthMobileCalendarRouteImport } from './routes/_auth/mobile/calendar'
import { Route as AuthMobileEventIdRouteImport } from './routes/_auth/mobile/$eventId'
import { Route as AuthSidebarLayoutPackageRouteImport } from './routes/_auth/_sidebarLayout/package'
import { Route as AuthSidebarLayoutEquipmentRouteImport } from './routes/_auth/_sidebarLayout/equipment'
import { Route as AuthSidebarLayoutStaffIndexRouteImport } from './routes/_auth/_sidebarLayout/staff/index'
import { Route as AuthSidebarLayoutOutsourceIndexRouteImport } from './routes/_auth/_sidebarLayout/outsource/index'
import { Route as AuthSidebarLayoutEventIndexRouteImport } from './routes/_auth/_sidebarLayout/event/index'
import { Route as AuthSidebarLayoutCompanyIndexRouteImport } from './routes/_auth/_sidebarLayout/company/index'
import { Route as AuthSidebarLayoutStaffStaffIdRouteImport } from './routes/_auth/_sidebarLayout/staff/$staffId'
import { Route as AuthSidebarLayoutEventEventIdRouteImport } from './routes/_auth/_sidebarLayout/event/$eventId'
import { Route as AuthSidebarLayoutCompanyCompanyIdRouteImport } from './routes/_auth/_sidebarLayout/company/$companyId'
import { Route as AuthAdminStaffCreateRouteImport } from './routes/_auth/_admin/staff/create'
import { Route as AuthAdminPackageCreateRouteImport } from './routes/_auth/_admin/package/create'
import { Route as AuthAdminOutsourceCreateRouteImport } from './routes/_auth/_admin/outsource/create'
import { Route as AuthAdminEventCreateRouteImport } from './routes/_auth/_admin/event/create'
import { Route as AuthAdminEquipmentCreateRouteImport } from './routes/_auth/_admin/equipment/create'
import { Route as AuthAdminCompanyCreateRouteImport } from './routes/_auth/_admin/company/create'
import { Route as AuthAdminStaffStaffIdEditRouteImport } from './routes/_auth/_admin/staff/$staffId/edit'
import { Route as AuthAdminPackagePackageIdEditRouteImport } from './routes/_auth/_admin/package/$packageId/edit'
import { Route as AuthAdminOutsourceOutsourceIdEditRouteImport } from './routes/_auth/_admin/outsource/$outsourceId/edit'
import { Route as AuthAdminEventEventIdEditRouteImport } from './routes/_auth/_admin/event/$eventId/edit'
import { Route as AuthAdminEquipmentEquipmentIdEditRouteImport } from './routes/_auth/_admin/equipment/$equipmentId/edit'
import { Route as AuthAdminCompanyCompanyIdEditRouteImport } from './routes/_auth/_admin/company/$companyId/edit'

const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSetPasswordRoute = AuthSetPasswordRouteImport.update({
  id: '/auth/set-password',
  path: '/auth/set-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthMobileRouteRoute = AuthMobileRouteRouteImport.update({
  id: '/mobile',
  path: '/mobile',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSidebarLayoutRouteRoute = AuthSidebarLayoutRouteRouteImport.update({
  id: '/_sidebarLayout',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthAdminRouteRoute = AuthAdminRouteRouteImport.update({
  id: '/_admin',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthMobileIndexRoute = AuthMobileIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthMobileRouteRoute,
} as any)
const AuthSidebarLayoutIndexRoute = AuthSidebarLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthSidebarLayoutRouteRoute,
} as any)
const AuthProfileChangePasswordRoute =
  AuthProfileChangePasswordRouteImport.update({
    id: '/profile/change-password',
    path: '/profile/change-password',
    getParentRoute: () => AuthRouteRoute,
  } as any)
const AuthMobileProfileRoute = AuthMobileProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthMobileRouteRoute,
} as any)
const AuthMobileCalendarRoute = AuthMobileCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AuthMobileRouteRoute,
} as any)
const AuthMobileEventIdRoute = AuthMobileEventIdRouteImport.update({
  id: '/$eventId',
  path: '/$eventId',
  getParentRoute: () => AuthMobileRouteRoute,
} as any)
const AuthSidebarLayoutPackageRoute =
  AuthSidebarLayoutPackageRouteImport.update({
    id: '/package',
    path: '/package',
    getParentRoute: () => AuthSidebarLayoutRouteRoute,
  } as any)
const AuthSidebarLayoutEquipmentRoute =
  AuthSidebarLayoutEquipmentRouteImport.update({
    id: '/equipment',
    path: '/equipment',
    getParentRoute: () => AuthSidebarLayoutRouteRoute,
  } as any)
const AuthSidebarLayoutStaffIndexRoute =
  AuthSidebarLayoutStaffIndexRouteImport.update({
    id: '/staff/',
    path: '/staff/',
    getParentRoute: () => AuthSidebarLayoutRouteRoute,
  } as any)
const AuthSidebarLayoutOutsourceIndexRoute =
  AuthSidebarLayoutOutsourceIndexRouteImport.update({
    id: '/outsource/',
    path: '/outsource/',
    getParentRoute: () => AuthSidebarLayoutRouteRoute,
  } as any)
const AuthSidebarLayoutEventIndexRoute =
  AuthSidebarLayoutEventIndexRouteImport.update({
    id: '/event/',
    path: '/event/',
    getParentRoute: () => AuthSidebarLayoutRouteRoute,
  } as any)
const AuthSidebarLayoutCompanyIndexRoute =
  AuthSidebarLayoutCompanyIndexRouteImport.update({
    id: '/company/',
    path: '/company/',
    getParentRoute: () => AuthSidebarLayoutRouteRoute,
  } as any)
const AuthSidebarLayoutStaffStaffIdRoute =
  AuthSidebarLayoutStaffStaffIdRouteImport.update({
    id: '/staff/$staffId',
    path: '/staff/$staffId',
    getParentRoute: () => AuthSidebarLayoutRouteRoute,
  } as any)
const AuthSidebarLayoutEventEventIdRoute =
  AuthSidebarLayoutEventEventIdRouteImport.update({
    id: '/event/$eventId',
    path: '/event/$eventId',
    getParentRoute: () => AuthSidebarLayoutRouteRoute,
  } as any)
const AuthSidebarLayoutCompanyCompanyIdRoute =
  AuthSidebarLayoutCompanyCompanyIdRouteImport.update({
    id: '/company/$companyId',
    path: '/company/$companyId',
    getParentRoute: () => AuthSidebarLayoutRouteRoute,
  } as any)
const AuthAdminStaffCreateRoute = AuthAdminStaffCreateRouteImport.update({
  id: '/staff/create',
  path: '/staff/create',
  getParentRoute: () => AuthAdminRouteRoute,
} as any)
const AuthAdminPackageCreateRoute = AuthAdminPackageCreateRouteImport.update({
  id: '/package/create',
  path: '/package/create',
  getParentRoute: () => AuthAdminRouteRoute,
} as any)
const AuthAdminOutsourceCreateRoute =
  AuthAdminOutsourceCreateRouteImport.update({
    id: '/outsource/create',
    path: '/outsource/create',
    getParentRoute: () => AuthAdminRouteRoute,
  } as any)
const AuthAdminEventCreateRoute = AuthAdminEventCreateRouteImport.update({
  id: '/event/create',
  path: '/event/create',
  getParentRoute: () => AuthAdminRouteRoute,
} as any)
const AuthAdminEquipmentCreateRoute =
  AuthAdminEquipmentCreateRouteImport.update({
    id: '/equipment/create',
    path: '/equipment/create',
    getParentRoute: () => AuthAdminRouteRoute,
  } as any)
const AuthAdminCompanyCreateRoute = AuthAdminCompanyCreateRouteImport.update({
  id: '/company/create',
  path: '/company/create',
  getParentRoute: () => AuthAdminRouteRoute,
} as any)
const AuthAdminStaffStaffIdEditRoute =
  AuthAdminStaffStaffIdEditRouteImport.update({
    id: '/staff/$staffId/edit',
    path: '/staff/$staffId/edit',
    getParentRoute: () => AuthAdminRouteRoute,
  } as any)
const AuthAdminPackagePackageIdEditRoute =
  AuthAdminPackagePackageIdEditRouteImport.update({
    id: '/package/$packageId/edit',
    path: '/package/$packageId/edit',
    getParentRoute: () => AuthAdminRouteRoute,
  } as any)
const AuthAdminOutsourceOutsourceIdEditRoute =
  AuthAdminOutsourceOutsourceIdEditRouteImport.update({
    id: '/outsource/$outsourceId/edit',
    path: '/outsource/$outsourceId/edit',
    getParentRoute: () => AuthAdminRouteRoute,
  } as any)
const AuthAdminEventEventIdEditRoute =
  AuthAdminEventEventIdEditRouteImport.update({
    id: '/event/$eventId/edit',
    path: '/event/$eventId/edit',
    getParentRoute: () => AuthAdminRouteRoute,
  } as any)
const AuthAdminEquipmentEquipmentIdEditRoute =
  AuthAdminEquipmentEquipmentIdEditRouteImport.update({
    id: '/equipment/$equipmentId/edit',
    path: '/equipment/$equipmentId/edit',
    getParentRoute: () => AuthAdminRouteRoute,
  } as any)
const AuthAdminCompanyCompanyIdEditRoute =
  AuthAdminCompanyCompanyIdEditRouteImport.update({
    id: '/company/$companyId/edit',
    path: '/company/$companyId/edit',
    getParentRoute: () => AuthAdminRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/mobile': typeof AuthMobileRouteRouteWithChildren
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/set-password': typeof AuthSetPasswordRoute
  '/login': typeof LoginIndexRoute
  '/equipment': typeof AuthSidebarLayoutEquipmentRoute
  '/package': typeof AuthSidebarLayoutPackageRoute
  '/mobile/$eventId': typeof AuthMobileEventIdRoute
  '/mobile/calendar': typeof AuthMobileCalendarRoute
  '/mobile/profile': typeof AuthMobileProfileRoute
  '/profile/change-password': typeof AuthProfileChangePasswordRoute
  '/': typeof AuthSidebarLayoutIndexRoute
  '/mobile/': typeof AuthMobileIndexRoute
  '/company/create': typeof AuthAdminCompanyCreateRoute
  '/equipment/create': typeof AuthAdminEquipmentCreateRoute
  '/event/create': typeof AuthAdminEventCreateRoute
  '/outsource/create': typeof AuthAdminOutsourceCreateRoute
  '/package/create': typeof AuthAdminPackageCreateRoute
  '/staff/create': typeof AuthAdminStaffCreateRoute
  '/company/$companyId': typeof AuthSidebarLayoutCompanyCompanyIdRoute
  '/event/$eventId': typeof AuthSidebarLayoutEventEventIdRoute
  '/staff/$staffId': typeof AuthSidebarLayoutStaffStaffIdRoute
  '/company': typeof AuthSidebarLayoutCompanyIndexRoute
  '/event': typeof AuthSidebarLayoutEventIndexRoute
  '/outsource': typeof AuthSidebarLayoutOutsourceIndexRoute
  '/staff': typeof AuthSidebarLayoutStaffIndexRoute
  '/company/$companyId/edit': typeof AuthAdminCompanyCompanyIdEditRoute
  '/equipment/$equipmentId/edit': typeof AuthAdminEquipmentEquipmentIdEditRoute
  '/event/$eventId/edit': typeof AuthAdminEventEventIdEditRoute
  '/outsource/$outsourceId/edit': typeof AuthAdminOutsourceOutsourceIdEditRoute
  '/package/$packageId/edit': typeof AuthAdminPackagePackageIdEditRoute
  '/staff/$staffId/edit': typeof AuthAdminStaffStaffIdEditRoute
}
export interface FileRoutesByTo {
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/set-password': typeof AuthSetPasswordRoute
  '/login': typeof LoginIndexRoute
  '/equipment': typeof AuthSidebarLayoutEquipmentRoute
  '/package': typeof AuthSidebarLayoutPackageRoute
  '/mobile/$eventId': typeof AuthMobileEventIdRoute
  '/mobile/calendar': typeof AuthMobileCalendarRoute
  '/mobile/profile': typeof AuthMobileProfileRoute
  '/profile/change-password': typeof AuthProfileChangePasswordRoute
  '/': typeof AuthSidebarLayoutIndexRoute
  '/mobile': typeof AuthMobileIndexRoute
  '/company/create': typeof AuthAdminCompanyCreateRoute
  '/equipment/create': typeof AuthAdminEquipmentCreateRoute
  '/event/create': typeof AuthAdminEventCreateRoute
  '/outsource/create': typeof AuthAdminOutsourceCreateRoute
  '/package/create': typeof AuthAdminPackageCreateRoute
  '/staff/create': typeof AuthAdminStaffCreateRoute
  '/company/$companyId': typeof AuthSidebarLayoutCompanyCompanyIdRoute
  '/event/$eventId': typeof AuthSidebarLayoutEventEventIdRoute
  '/staff/$staffId': typeof AuthSidebarLayoutStaffStaffIdRoute
  '/company': typeof AuthSidebarLayoutCompanyIndexRoute
  '/event': typeof AuthSidebarLayoutEventIndexRoute
  '/outsource': typeof AuthSidebarLayoutOutsourceIndexRoute
  '/staff': typeof AuthSidebarLayoutStaffIndexRoute
  '/company/$companyId/edit': typeof AuthAdminCompanyCompanyIdEditRoute
  '/equipment/$equipmentId/edit': typeof AuthAdminEquipmentEquipmentIdEditRoute
  '/event/$eventId/edit': typeof AuthAdminEventEventIdEditRoute
  '/outsource/$outsourceId/edit': typeof AuthAdminOutsourceOutsourceIdEditRoute
  '/package/$packageId/edit': typeof AuthAdminPackagePackageIdEditRoute
  '/staff/$staffId/edit': typeof AuthAdminStaffStaffIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_auth/_admin': typeof AuthAdminRouteRouteWithChildren
  '/_auth/_sidebarLayout': typeof AuthSidebarLayoutRouteRouteWithChildren
  '/_auth/mobile': typeof AuthMobileRouteRouteWithChildren
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/set-password': typeof AuthSetPasswordRoute
  '/login/': typeof LoginIndexRoute
  '/_auth/_sidebarLayout/equipment': typeof AuthSidebarLayoutEquipmentRoute
  '/_auth/_sidebarLayout/package': typeof AuthSidebarLayoutPackageRoute
  '/_auth/mobile/$eventId': typeof AuthMobileEventIdRoute
  '/_auth/mobile/calendar': typeof AuthMobileCalendarRoute
  '/_auth/mobile/profile': typeof AuthMobileProfileRoute
  '/_auth/profile/change-password': typeof AuthProfileChangePasswordRoute
  '/_auth/_sidebarLayout/': typeof AuthSidebarLayoutIndexRoute
  '/_auth/mobile/': typeof AuthMobileIndexRoute
  '/_auth/_admin/company/create': typeof AuthAdminCompanyCreateRoute
  '/_auth/_admin/equipment/create': typeof AuthAdminEquipmentCreateRoute
  '/_auth/_admin/event/create': typeof AuthAdminEventCreateRoute
  '/_auth/_admin/outsource/create': typeof AuthAdminOutsourceCreateRoute
  '/_auth/_admin/package/create': typeof AuthAdminPackageCreateRoute
  '/_auth/_admin/staff/create': typeof AuthAdminStaffCreateRoute
  '/_auth/_sidebarLayout/company/$companyId': typeof AuthSidebarLayoutCompanyCompanyIdRoute
  '/_auth/_sidebarLayout/event/$eventId': typeof AuthSidebarLayoutEventEventIdRoute
  '/_auth/_sidebarLayout/staff/$staffId': typeof AuthSidebarLayoutStaffStaffIdRoute
  '/_auth/_sidebarLayout/company/': typeof AuthSidebarLayoutCompanyIndexRoute
  '/_auth/_sidebarLayout/event/': typeof AuthSidebarLayoutEventIndexRoute
  '/_auth/_sidebarLayout/outsource/': typeof AuthSidebarLayoutOutsourceIndexRoute
  '/_auth/_sidebarLayout/staff/': typeof AuthSidebarLayoutStaffIndexRoute
  '/_auth/_admin/company/$companyId/edit': typeof AuthAdminCompanyCompanyIdEditRoute
  '/_auth/_admin/equipment/$equipmentId/edit': typeof AuthAdminEquipmentEquipmentIdEditRoute
  '/_auth/_admin/event/$eventId/edit': typeof AuthAdminEventEventIdEditRoute
  '/_auth/_admin/outsource/$outsourceId/edit': typeof AuthAdminOutsourceOutsourceIdEditRoute
  '/_auth/_admin/package/$packageId/edit': typeof AuthAdminPackagePackageIdEditRoute
  '/_auth/_admin/staff/$staffId/edit': typeof AuthAdminStaffStaffIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/mobile'
    | '/auth/forgot-password'
    | '/auth/set-password'
    | '/login'
    | '/equipment'
    | '/package'
    | '/mobile/$eventId'
    | '/mobile/calendar'
    | '/mobile/profile'
    | '/profile/change-password'
    | '/'
    | '/mobile/'
    | '/company/create'
    | '/equipment/create'
    | '/event/create'
    | '/outsource/create'
    | '/package/create'
    | '/staff/create'
    | '/company/$companyId'
    | '/event/$eventId'
    | '/staff/$staffId'
    | '/company'
    | '/event'
    | '/outsource'
    | '/staff'
    | '/company/$companyId/edit'
    | '/equipment/$equipmentId/edit'
    | '/event/$eventId/edit'
    | '/outsource/$outsourceId/edit'
    | '/package/$packageId/edit'
    | '/staff/$staffId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth/forgot-password'
    | '/auth/set-password'
    | '/login'
    | '/equipment'
    | '/package'
    | '/mobile/$eventId'
    | '/mobile/calendar'
    | '/mobile/profile'
    | '/profile/change-password'
    | '/'
    | '/mobile'
    | '/company/create'
    | '/equipment/create'
    | '/event/create'
    | '/outsource/create'
    | '/package/create'
    | '/staff/create'
    | '/company/$companyId'
    | '/event/$eventId'
    | '/staff/$staffId'
    | '/company'
    | '/event'
    | '/outsource'
    | '/staff'
    | '/company/$companyId/edit'
    | '/equipment/$equipmentId/edit'
    | '/event/$eventId/edit'
    | '/outsource/$outsourceId/edit'
    | '/package/$packageId/edit'
    | '/staff/$staffId/edit'
  id:
    | '__root__'
    | '/_auth'
    | '/_auth/_admin'
    | '/_auth/_sidebarLayout'
    | '/_auth/mobile'
    | '/auth/forgot-password'
    | '/auth/set-password'
    | '/login/'
    | '/_auth/_sidebarLayout/equipment'
    | '/_auth/_sidebarLayout/package'
    | '/_auth/mobile/$eventId'
    | '/_auth/mobile/calendar'
    | '/_auth/mobile/profile'
    | '/_auth/profile/change-password'
    | '/_auth/_sidebarLayout/'
    | '/_auth/mobile/'
    | '/_auth/_admin/company/create'
    | '/_auth/_admin/equipment/create'
    | '/_auth/_admin/event/create'
    | '/_auth/_admin/outsource/create'
    | '/_auth/_admin/package/create'
    | '/_auth/_admin/staff/create'
    | '/_auth/_sidebarLayout/company/$companyId'
    | '/_auth/_sidebarLayout/event/$eventId'
    | '/_auth/_sidebarLayout/staff/$staffId'
    | '/_auth/_sidebarLayout/company/'
    | '/_auth/_sidebarLayout/event/'
    | '/_auth/_sidebarLayout/outsource/'
    | '/_auth/_sidebarLayout/staff/'
    | '/_auth/_admin/company/$companyId/edit'
    | '/_auth/_admin/equipment/$equipmentId/edit'
    | '/_auth/_admin/event/$eventId/edit'
    | '/_auth/_admin/outsource/$outsourceId/edit'
    | '/_auth/_admin/package/$packageId/edit'
    | '/_auth/_admin/staff/$staffId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthSetPasswordRoute: typeof AuthSetPasswordRoute
  LoginIndexRoute: typeof LoginIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/set-password': {
      id: '/auth/set-password'
      path: '/auth/set-password'
      fullPath: '/auth/set-password'
      preLoaderRoute: typeof AuthSetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/mobile': {
      id: '/_auth/mobile'
      path: '/mobile'
      fullPath: '/mobile'
      preLoaderRoute: typeof AuthMobileRouteRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/_sidebarLayout': {
      id: '/_auth/_sidebarLayout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthSidebarLayoutRouteRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/_admin': {
      id: '/_auth/_admin'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthAdminRouteRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/mobile/': {
      id: '/_auth/mobile/'
      path: '/'
      fullPath: '/mobile/'
      preLoaderRoute: typeof AuthMobileIndexRouteImport
      parentRoute: typeof AuthMobileRouteRoute
    }
    '/_auth/_sidebarLayout/': {
      id: '/_auth/_sidebarLayout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthSidebarLayoutIndexRouteImport
      parentRoute: typeof AuthSidebarLayoutRouteRoute
    }
    '/_auth/profile/change-password': {
      id: '/_auth/profile/change-password'
      path: '/profile/change-password'
      fullPath: '/profile/change-password'
      preLoaderRoute: typeof AuthProfileChangePasswordRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/mobile/profile': {
      id: '/_auth/mobile/profile'
      path: '/profile'
      fullPath: '/mobile/profile'
      preLoaderRoute: typeof AuthMobileProfileRouteImport
      parentRoute: typeof AuthMobileRouteRoute
    }
    '/_auth/mobile/calendar': {
      id: '/_auth/mobile/calendar'
      path: '/calendar'
      fullPath: '/mobile/calendar'
      preLoaderRoute: typeof AuthMobileCalendarRouteImport
      parentRoute: typeof AuthMobileRouteRoute
    }
    '/_auth/mobile/$eventId': {
      id: '/_auth/mobile/$eventId'
      path: '/$eventId'
      fullPath: '/mobile/$eventId'
      preLoaderRoute: typeof AuthMobileEventIdRouteImport
      parentRoute: typeof AuthMobileRouteRoute
    }
    '/_auth/_sidebarLayout/package': {
      id: '/_auth/_sidebarLayout/package'
      path: '/package'
      fullPath: '/package'
      preLoaderRoute: typeof AuthSidebarLayoutPackageRouteImport
      parentRoute: typeof AuthSidebarLayoutRouteRoute
    }
    '/_auth/_sidebarLayout/equipment': {
      id: '/_auth/_sidebarLayout/equipment'
      path: '/equipment'
      fullPath: '/equipment'
      preLoaderRoute: typeof AuthSidebarLayoutEquipmentRouteImport
      parentRoute: typeof AuthSidebarLayoutRouteRoute
    }
    '/_auth/_sidebarLayout/staff/': {
      id: '/_auth/_sidebarLayout/staff/'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof AuthSidebarLayoutStaffIndexRouteImport
      parentRoute: typeof AuthSidebarLayoutRouteRoute
    }
    '/_auth/_sidebarLayout/outsource/': {
      id: '/_auth/_sidebarLayout/outsource/'
      path: '/outsource'
      fullPath: '/outsource'
      preLoaderRoute: typeof AuthSidebarLayoutOutsourceIndexRouteImport
      parentRoute: typeof AuthSidebarLayoutRouteRoute
    }
    '/_auth/_sidebarLayout/event/': {
      id: '/_auth/_sidebarLayout/event/'
      path: '/event'
      fullPath: '/event'
      preLoaderRoute: typeof AuthSidebarLayoutEventIndexRouteImport
      parentRoute: typeof AuthSidebarLayoutRouteRoute
    }
    '/_auth/_sidebarLayout/company/': {
      id: '/_auth/_sidebarLayout/company/'
      path: '/company'
      fullPath: '/company'
      preLoaderRoute: typeof AuthSidebarLayoutCompanyIndexRouteImport
      parentRoute: typeof AuthSidebarLayoutRouteRoute
    }
    '/_auth/_sidebarLayout/staff/$staffId': {
      id: '/_auth/_sidebarLayout/staff/$staffId'
      path: '/staff/$staffId'
      fullPath: '/staff/$staffId'
      preLoaderRoute: typeof AuthSidebarLayoutStaffStaffIdRouteImport
      parentRoute: typeof AuthSidebarLayoutRouteRoute
    }
    '/_auth/_sidebarLayout/event/$eventId': {
      id: '/_auth/_sidebarLayout/event/$eventId'
      path: '/event/$eventId'
      fullPath: '/event/$eventId'
      preLoaderRoute: typeof AuthSidebarLayoutEventEventIdRouteImport
      parentRoute: typeof AuthSidebarLayoutRouteRoute
    }
    '/_auth/_sidebarLayout/company/$companyId': {
      id: '/_auth/_sidebarLayout/company/$companyId'
      path: '/company/$companyId'
      fullPath: '/company/$companyId'
      preLoaderRoute: typeof AuthSidebarLayoutCompanyCompanyIdRouteImport
      parentRoute: typeof AuthSidebarLayoutRouteRoute
    }
    '/_auth/_admin/staff/create': {
      id: '/_auth/_admin/staff/create'
      path: '/staff/create'
      fullPath: '/staff/create'
      preLoaderRoute: typeof AuthAdminStaffCreateRouteImport
      parentRoute: typeof AuthAdminRouteRoute
    }
    '/_auth/_admin/package/create': {
      id: '/_auth/_admin/package/create'
      path: '/package/create'
      fullPath: '/package/create'
      preLoaderRoute: typeof AuthAdminPackageCreateRouteImport
      parentRoute: typeof AuthAdminRouteRoute
    }
    '/_auth/_admin/outsource/create': {
      id: '/_auth/_admin/outsource/create'
      path: '/outsource/create'
      fullPath: '/outsource/create'
      preLoaderRoute: typeof AuthAdminOutsourceCreateRouteImport
      parentRoute: typeof AuthAdminRouteRoute
    }
    '/_auth/_admin/event/create': {
      id: '/_auth/_admin/event/create'
      path: '/event/create'
      fullPath: '/event/create'
      preLoaderRoute: typeof AuthAdminEventCreateRouteImport
      parentRoute: typeof AuthAdminRouteRoute
    }
    '/_auth/_admin/equipment/create': {
      id: '/_auth/_admin/equipment/create'
      path: '/equipment/create'
      fullPath: '/equipment/create'
      preLoaderRoute: typeof AuthAdminEquipmentCreateRouteImport
      parentRoute: typeof AuthAdminRouteRoute
    }
    '/_auth/_admin/company/create': {
      id: '/_auth/_admin/company/create'
      path: '/company/create'
      fullPath: '/company/create'
      preLoaderRoute: typeof AuthAdminCompanyCreateRouteImport
      parentRoute: typeof AuthAdminRouteRoute
    }
    '/_auth/_admin/staff/$staffId/edit': {
      id: '/_auth/_admin/staff/$staffId/edit'
      path: '/staff/$staffId/edit'
      fullPath: '/staff/$staffId/edit'
      preLoaderRoute: typeof AuthAdminStaffStaffIdEditRouteImport
      parentRoute: typeof AuthAdminRouteRoute
    }
    '/_auth/_admin/package/$packageId/edit': {
      id: '/_auth/_admin/package/$packageId/edit'
      path: '/package/$packageId/edit'
      fullPath: '/package/$packageId/edit'
      preLoaderRoute: typeof AuthAdminPackagePackageIdEditRouteImport
      parentRoute: typeof AuthAdminRouteRoute
    }
    '/_auth/_admin/outsource/$outsourceId/edit': {
      id: '/_auth/_admin/outsource/$outsourceId/edit'
      path: '/outsource/$outsourceId/edit'
      fullPath: '/outsource/$outsourceId/edit'
      preLoaderRoute: typeof AuthAdminOutsourceOutsourceIdEditRouteImport
      parentRoute: typeof AuthAdminRouteRoute
    }
    '/_auth/_admin/event/$eventId/edit': {
      id: '/_auth/_admin/event/$eventId/edit'
      path: '/event/$eventId/edit'
      fullPath: '/event/$eventId/edit'
      preLoaderRoute: typeof AuthAdminEventEventIdEditRouteImport
      parentRoute: typeof AuthAdminRouteRoute
    }
    '/_auth/_admin/equipment/$equipmentId/edit': {
      id: '/_auth/_admin/equipment/$equipmentId/edit'
      path: '/equipment/$equipmentId/edit'
      fullPath: '/equipment/$equipmentId/edit'
      preLoaderRoute: typeof AuthAdminEquipmentEquipmentIdEditRouteImport
      parentRoute: typeof AuthAdminRouteRoute
    }
    '/_auth/_admin/company/$companyId/edit': {
      id: '/_auth/_admin/company/$companyId/edit'
      path: '/company/$companyId/edit'
      fullPath: '/company/$companyId/edit'
      preLoaderRoute: typeof AuthAdminCompanyCompanyIdEditRouteImport
      parentRoute: typeof AuthAdminRouteRoute
    }
  }
}

interface AuthAdminRouteRouteChildren {
  AuthAdminCompanyCreateRoute: typeof AuthAdminCompanyCreateRoute
  AuthAdminEquipmentCreateRoute: typeof AuthAdminEquipmentCreateRoute
  AuthAdminEventCreateRoute: typeof AuthAdminEventCreateRoute
  AuthAdminOutsourceCreateRoute: typeof AuthAdminOutsourceCreateRoute
  AuthAdminPackageCreateRoute: typeof AuthAdminPackageCreateRoute
  AuthAdminStaffCreateRoute: typeof AuthAdminStaffCreateRoute
  AuthAdminCompanyCompanyIdEditRoute: typeof AuthAdminCompanyCompanyIdEditRoute
  AuthAdminEquipmentEquipmentIdEditRoute: typeof AuthAdminEquipmentEquipmentIdEditRoute
  AuthAdminEventEventIdEditRoute: typeof AuthAdminEventEventIdEditRoute
  AuthAdminOutsourceOutsourceIdEditRoute: typeof AuthAdminOutsourceOutsourceIdEditRoute
  AuthAdminPackagePackageIdEditRoute: typeof AuthAdminPackagePackageIdEditRoute
  AuthAdminStaffStaffIdEditRoute: typeof AuthAdminStaffStaffIdEditRoute
}

const AuthAdminRouteRouteChildren: AuthAdminRouteRouteChildren = {
  AuthAdminCompanyCreateRoute: AuthAdminCompanyCreateRoute,
  AuthAdminEquipmentCreateRoute: AuthAdminEquipmentCreateRoute,
  AuthAdminEventCreateRoute: AuthAdminEventCreateRoute,
  AuthAdminOutsourceCreateRoute: AuthAdminOutsourceCreateRoute,
  AuthAdminPackageCreateRoute: AuthAdminPackageCreateRoute,
  AuthAdminStaffCreateRoute: AuthAdminStaffCreateRoute,
  AuthAdminCompanyCompanyIdEditRoute: AuthAdminCompanyCompanyIdEditRoute,
  AuthAdminEquipmentEquipmentIdEditRoute:
    AuthAdminEquipmentEquipmentIdEditRoute,
  AuthAdminEventEventIdEditRoute: AuthAdminEventEventIdEditRoute,
  AuthAdminOutsourceOutsourceIdEditRoute:
    AuthAdminOutsourceOutsourceIdEditRoute,
  AuthAdminPackagePackageIdEditRoute: AuthAdminPackagePackageIdEditRoute,
  AuthAdminStaffStaffIdEditRoute: AuthAdminStaffStaffIdEditRoute,
}

const AuthAdminRouteRouteWithChildren = AuthAdminRouteRoute._addFileChildren(
  AuthAdminRouteRouteChildren,
)

interface AuthSidebarLayoutRouteRouteChildren {
  AuthSidebarLayoutEquipmentRoute: typeof AuthSidebarLayoutEquipmentRoute
  AuthSidebarLayoutPackageRoute: typeof AuthSidebarLayoutPackageRoute
  AuthSidebarLayoutIndexRoute: typeof AuthSidebarLayoutIndexRoute
  AuthSidebarLayoutCompanyCompanyIdRoute: typeof AuthSidebarLayoutCompanyCompanyIdRoute
  AuthSidebarLayoutEventEventIdRoute: typeof AuthSidebarLayoutEventEventIdRoute
  AuthSidebarLayoutStaffStaffIdRoute: typeof AuthSidebarLayoutStaffStaffIdRoute
  AuthSidebarLayoutCompanyIndexRoute: typeof AuthSidebarLayoutCompanyIndexRoute
  AuthSidebarLayoutEventIndexRoute: typeof AuthSidebarLayoutEventIndexRoute
  AuthSidebarLayoutOutsourceIndexRoute: typeof AuthSidebarLayoutOutsourceIndexRoute
  AuthSidebarLayoutStaffIndexRoute: typeof AuthSidebarLayoutStaffIndexRoute
}

const AuthSidebarLayoutRouteRouteChildren: AuthSidebarLayoutRouteRouteChildren =
  {
    AuthSidebarLayoutEquipmentRoute: AuthSidebarLayoutEquipmentRoute,
    AuthSidebarLayoutPackageRoute: AuthSidebarLayoutPackageRoute,
    AuthSidebarLayoutIndexRoute: AuthSidebarLayoutIndexRoute,
    AuthSidebarLayoutCompanyCompanyIdRoute:
      AuthSidebarLayoutCompanyCompanyIdRoute,
    AuthSidebarLayoutEventEventIdRoute: AuthSidebarLayoutEventEventIdRoute,
    AuthSidebarLayoutStaffStaffIdRoute: AuthSidebarLayoutStaffStaffIdRoute,
    AuthSidebarLayoutCompanyIndexRoute: AuthSidebarLayoutCompanyIndexRoute,
    AuthSidebarLayoutEventIndexRoute: AuthSidebarLayoutEventIndexRoute,
    AuthSidebarLayoutOutsourceIndexRoute: AuthSidebarLayoutOutsourceIndexRoute,
    AuthSidebarLayoutStaffIndexRoute: AuthSidebarLayoutStaffIndexRoute,
  }

const AuthSidebarLayoutRouteRouteWithChildren =
  AuthSidebarLayoutRouteRoute._addFileChildren(
    AuthSidebarLayoutRouteRouteChildren,
  )

interface AuthMobileRouteRouteChildren {
  AuthMobileEventIdRoute: typeof AuthMobileEventIdRoute
  AuthMobileCalendarRoute: typeof AuthMobileCalendarRoute
  AuthMobileProfileRoute: typeof AuthMobileProfileRoute
  AuthMobileIndexRoute: typeof AuthMobileIndexRoute
}

const AuthMobileRouteRouteChildren: AuthMobileRouteRouteChildren = {
  AuthMobileEventIdRoute: AuthMobileEventIdRoute,
  AuthMobileCalendarRoute: AuthMobileCalendarRoute,
  AuthMobileProfileRoute: AuthMobileProfileRoute,
  AuthMobileIndexRoute: AuthMobileIndexRoute,
}

const AuthMobileRouteRouteWithChildren = AuthMobileRouteRoute._addFileChildren(
  AuthMobileRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthAdminRouteRoute: typeof AuthAdminRouteRouteWithChildren
  AuthSidebarLayoutRouteRoute: typeof AuthSidebarLayoutRouteRouteWithChildren
  AuthMobileRouteRoute: typeof AuthMobileRouteRouteWithChildren
  AuthProfileChangePasswordRoute: typeof AuthProfileChangePasswordRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthAdminRouteRoute: AuthAdminRouteRouteWithChildren,
  AuthSidebarLayoutRouteRoute: AuthSidebarLayoutRouteRouteWithChildren,
  AuthMobileRouteRoute: AuthMobileRouteRouteWithChildren,
  AuthProfileChangePasswordRoute: AuthProfileChangePasswordRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthRouteRoute: AuthRouteRouteWithChildren,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthSetPasswordRoute: AuthSetPasswordRoute,
  LoginIndexRoute: LoginIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
