/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as AuthSidebarLayoutRouteRouteImport } from './routes/_auth/_sidebarLayout/route'
import { Route as AuthSidebarLayoutIndexRouteImport } from './routes/_auth/_sidebarLayout/index'
import { Route as AuthStaffCreateRouteImport } from './routes/_auth/staff/create'
import { Route as AuthPackageCreateRouteImport } from './routes/_auth/package/create'
import { Route as AuthOutsourceCreateRouteImport } from './routes/_auth/outsource/create'
import { Route as AuthEventCreateRouteImport } from './routes/_auth/event/create'
import { Route as AuthEquipmentCreateRouteImport } from './routes/_auth/equipment/create'
import { Route as AuthCompanyCreateRouteImport } from './routes/_auth/company/create'
import { Route as AuthSidebarLayoutPackageRouteImport } from './routes/_auth/_sidebarLayout/package'
import { Route as AuthSidebarLayoutEquipmentRouteImport } from './routes/_auth/_sidebarLayout/equipment'
import { Route as AuthSidebarLayoutStaffIndexRouteImport } from './routes/_auth/_sidebarLayout/staff/index'
import { Route as AuthSidebarLayoutOutsourceIndexRouteImport } from './routes/_auth/_sidebarLayout/outsource/index'
import { Route as AuthSidebarLayoutEventIndexRouteImport } from './routes/_auth/_sidebarLayout/event/index'
import { Route as AuthSidebarLayoutCompanyIndexRouteImport } from './routes/_auth/_sidebarLayout/company/index'
import { Route as AuthStaffStaffIdEditRouteImport } from './routes/_auth/staff/$staffId/edit'
import { Route as AuthPackagePackageIdEditRouteImport } from './routes/_auth/package/$packageId/edit'
import { Route as AuthOutsourceOutsourceIdEditRouteImport } from './routes/_auth/outsource/$outsourceId/edit'
import { Route as AuthEventEventIdEditRouteImport } from './routes/_auth/event/$eventId/edit'
import { Route as AuthEquipmentEquipmentIdEditRouteImport } from './routes/_auth/equipment/$equipmentId/edit'
import { Route as AuthCompanyCompanyIdEditRouteImport } from './routes/_auth/company/$companyId/edit'
import { Route as AuthSidebarLayoutStaffStaffIdRouteImport } from './routes/_auth/_sidebarLayout/staff/$staffId'
import { Route as AuthSidebarLayoutEventEventIdRouteImport } from './routes/_auth/_sidebarLayout/event/$eventId'
import { Route as AuthSidebarLayoutCompanyCompanyIdRouteImport } from './routes/_auth/_sidebarLayout/company/$companyId'

const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSidebarLayoutRouteRoute = AuthSidebarLayoutRouteRouteImport.update({
  id: '/_sidebarLayout',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSidebarLayoutIndexRoute = AuthSidebarLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthSidebarLayoutRouteRoute,
} as any)
const AuthStaffCreateRoute = AuthStaffCreateRouteImport.update({
  id: '/staff/create',
  path: '/staff/create',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthPackageCreateRoute = AuthPackageCreateRouteImport.update({
  id: '/package/create',
  path: '/package/create',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthOutsourceCreateRoute = AuthOutsourceCreateRouteImport.update({
  id: '/outsource/create',
  path: '/outsource/create',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthEventCreateRoute = AuthEventCreateRouteImport.update({
  id: '/event/create',
  path: '/event/create',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthEquipmentCreateRoute = AuthEquipmentCreateRouteImport.update({
  id: '/equipment/create',
  path: '/equipment/create',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthCompanyCreateRoute = AuthCompanyCreateRouteImport.update({
  id: '/company/create',
  path: '/company/create',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSidebarLayoutPackageRoute =
  AuthSidebarLayoutPackageRouteImport.update({
    id: '/package',
    path: '/package',
    getParentRoute: () => AuthSidebarLayoutRouteRoute,
  } as any)
const AuthSidebarLayoutEquipmentRoute =
  AuthSidebarLayoutEquipmentRouteImport.update({
    id: '/equipment',
    path: '/equipment',
    getParentRoute: () => AuthSidebarLayoutRouteRoute,
  } as any)
const AuthSidebarLayoutStaffIndexRoute =
  AuthSidebarLayoutStaffIndexRouteImport.update({
    id: '/staff/',
    path: '/staff/',
    getParentRoute: () => AuthSidebarLayoutRouteRoute,
  } as any)
const AuthSidebarLayoutOutsourceIndexRoute =
  AuthSidebarLayoutOutsourceIndexRouteImport.update({
    id: '/outsource/',
    path: '/outsource/',
    getParentRoute: () => AuthSidebarLayoutRouteRoute,
  } as any)
const AuthSidebarLayoutEventIndexRoute =
  AuthSidebarLayoutEventIndexRouteImport.update({
    id: '/event/',
    path: '/event/',
    getParentRoute: () => AuthSidebarLayoutRouteRoute,
  } as any)
const AuthSidebarLayoutCompanyIndexRoute =
  AuthSidebarLayoutCompanyIndexRouteImport.update({
    id: '/company/',
    path: '/company/',
    getParentRoute: () => AuthSidebarLayoutRouteRoute,
  } as any)
const AuthStaffStaffIdEditRoute = AuthStaffStaffIdEditRouteImport.update({
  id: '/staff/$staffId/edit',
  path: '/staff/$staffId/edit',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthPackagePackageIdEditRoute =
  AuthPackagePackageIdEditRouteImport.update({
    id: '/package/$packageId/edit',
    path: '/package/$packageId/edit',
    getParentRoute: () => AuthRouteRoute,
  } as any)
const AuthOutsourceOutsourceIdEditRoute =
  AuthOutsourceOutsourceIdEditRouteImport.update({
    id: '/outsource/$outsourceId/edit',
    path: '/outsource/$outsourceId/edit',
    getParentRoute: () => AuthRouteRoute,
  } as any)
const AuthEventEventIdEditRoute = AuthEventEventIdEditRouteImport.update({
  id: '/event/$eventId/edit',
  path: '/event/$eventId/edit',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthEquipmentEquipmentIdEditRoute =
  AuthEquipmentEquipmentIdEditRouteImport.update({
    id: '/equipment/$equipmentId/edit',
    path: '/equipment/$equipmentId/edit',
    getParentRoute: () => AuthRouteRoute,
  } as any)
const AuthCompanyCompanyIdEditRoute =
  AuthCompanyCompanyIdEditRouteImport.update({
    id: '/company/$companyId/edit',
    path: '/company/$companyId/edit',
    getParentRoute: () => AuthRouteRoute,
  } as any)
const AuthSidebarLayoutStaffStaffIdRoute =
  AuthSidebarLayoutStaffStaffIdRouteImport.update({
    id: '/staff/$staffId',
    path: '/staff/$staffId',
    getParentRoute: () => AuthSidebarLayoutRouteRoute,
  } as any)
const AuthSidebarLayoutEventEventIdRoute =
  AuthSidebarLayoutEventEventIdRouteImport.update({
    id: '/event/$eventId',
    path: '/event/$eventId',
    getParentRoute: () => AuthSidebarLayoutRouteRoute,
  } as any)
const AuthSidebarLayoutCompanyCompanyIdRoute =
  AuthSidebarLayoutCompanyCompanyIdRouteImport.update({
    id: '/company/$companyId',
    path: '/company/$companyId',
    getParentRoute: () => AuthSidebarLayoutRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginIndexRoute
  '/equipment': typeof AuthSidebarLayoutEquipmentRoute
  '/package': typeof AuthSidebarLayoutPackageRoute
  '/company/create': typeof AuthCompanyCreateRoute
  '/equipment/create': typeof AuthEquipmentCreateRoute
  '/event/create': typeof AuthEventCreateRoute
  '/outsource/create': typeof AuthOutsourceCreateRoute
  '/package/create': typeof AuthPackageCreateRoute
  '/staff/create': typeof AuthStaffCreateRoute
  '/': typeof AuthSidebarLayoutIndexRoute
  '/company/$companyId': typeof AuthSidebarLayoutCompanyCompanyIdRoute
  '/event/$eventId': typeof AuthSidebarLayoutEventEventIdRoute
  '/staff/$staffId': typeof AuthSidebarLayoutStaffStaffIdRoute
  '/company/$companyId/edit': typeof AuthCompanyCompanyIdEditRoute
  '/equipment/$equipmentId/edit': typeof AuthEquipmentEquipmentIdEditRoute
  '/event/$eventId/edit': typeof AuthEventEventIdEditRoute
  '/outsource/$outsourceId/edit': typeof AuthOutsourceOutsourceIdEditRoute
  '/package/$packageId/edit': typeof AuthPackagePackageIdEditRoute
  '/staff/$staffId/edit': typeof AuthStaffStaffIdEditRoute
  '/company': typeof AuthSidebarLayoutCompanyIndexRoute
  '/event': typeof AuthSidebarLayoutEventIndexRoute
  '/outsource': typeof AuthSidebarLayoutOutsourceIndexRoute
  '/staff': typeof AuthSidebarLayoutStaffIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginIndexRoute
  '/equipment': typeof AuthSidebarLayoutEquipmentRoute
  '/package': typeof AuthSidebarLayoutPackageRoute
  '/company/create': typeof AuthCompanyCreateRoute
  '/equipment/create': typeof AuthEquipmentCreateRoute
  '/event/create': typeof AuthEventCreateRoute
  '/outsource/create': typeof AuthOutsourceCreateRoute
  '/package/create': typeof AuthPackageCreateRoute
  '/staff/create': typeof AuthStaffCreateRoute
  '/': typeof AuthSidebarLayoutIndexRoute
  '/company/$companyId': typeof AuthSidebarLayoutCompanyCompanyIdRoute
  '/event/$eventId': typeof AuthSidebarLayoutEventEventIdRoute
  '/staff/$staffId': typeof AuthSidebarLayoutStaffStaffIdRoute
  '/company/$companyId/edit': typeof AuthCompanyCompanyIdEditRoute
  '/equipment/$equipmentId/edit': typeof AuthEquipmentEquipmentIdEditRoute
  '/event/$eventId/edit': typeof AuthEventEventIdEditRoute
  '/outsource/$outsourceId/edit': typeof AuthOutsourceOutsourceIdEditRoute
  '/package/$packageId/edit': typeof AuthPackagePackageIdEditRoute
  '/staff/$staffId/edit': typeof AuthStaffStaffIdEditRoute
  '/company': typeof AuthSidebarLayoutCompanyIndexRoute
  '/event': typeof AuthSidebarLayoutEventIndexRoute
  '/outsource': typeof AuthSidebarLayoutOutsourceIndexRoute
  '/staff': typeof AuthSidebarLayoutStaffIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_auth/_sidebarLayout': typeof AuthSidebarLayoutRouteRouteWithChildren
  '/login/': typeof LoginIndexRoute
  '/_auth/_sidebarLayout/equipment': typeof AuthSidebarLayoutEquipmentRoute
  '/_auth/_sidebarLayout/package': typeof AuthSidebarLayoutPackageRoute
  '/_auth/company/create': typeof AuthCompanyCreateRoute
  '/_auth/equipment/create': typeof AuthEquipmentCreateRoute
  '/_auth/event/create': typeof AuthEventCreateRoute
  '/_auth/outsource/create': typeof AuthOutsourceCreateRoute
  '/_auth/package/create': typeof AuthPackageCreateRoute
  '/_auth/staff/create': typeof AuthStaffCreateRoute
  '/_auth/_sidebarLayout/': typeof AuthSidebarLayoutIndexRoute
  '/_auth/_sidebarLayout/company/$companyId': typeof AuthSidebarLayoutCompanyCompanyIdRoute
  '/_auth/_sidebarLayout/event/$eventId': typeof AuthSidebarLayoutEventEventIdRoute
  '/_auth/_sidebarLayout/staff/$staffId': typeof AuthSidebarLayoutStaffStaffIdRoute
  '/_auth/company/$companyId/edit': typeof AuthCompanyCompanyIdEditRoute
  '/_auth/equipment/$equipmentId/edit': typeof AuthEquipmentEquipmentIdEditRoute
  '/_auth/event/$eventId/edit': typeof AuthEventEventIdEditRoute
  '/_auth/outsource/$outsourceId/edit': typeof AuthOutsourceOutsourceIdEditRoute
  '/_auth/package/$packageId/edit': typeof AuthPackagePackageIdEditRoute
  '/_auth/staff/$staffId/edit': typeof AuthStaffStaffIdEditRoute
  '/_auth/_sidebarLayout/company/': typeof AuthSidebarLayoutCompanyIndexRoute
  '/_auth/_sidebarLayout/event/': typeof AuthSidebarLayoutEventIndexRoute
  '/_auth/_sidebarLayout/outsource/': typeof AuthSidebarLayoutOutsourceIndexRoute
  '/_auth/_sidebarLayout/staff/': typeof AuthSidebarLayoutStaffIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/equipment'
    | '/package'
    | '/company/create'
    | '/equipment/create'
    | '/event/create'
    | '/outsource/create'
    | '/package/create'
    | '/staff/create'
    | '/'
    | '/company/$companyId'
    | '/event/$eventId'
    | '/staff/$staffId'
    | '/company/$companyId/edit'
    | '/equipment/$equipmentId/edit'
    | '/event/$eventId/edit'
    | '/outsource/$outsourceId/edit'
    | '/package/$packageId/edit'
    | '/staff/$staffId/edit'
    | '/company'
    | '/event'
    | '/outsource'
    | '/staff'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/equipment'
    | '/package'
    | '/company/create'
    | '/equipment/create'
    | '/event/create'
    | '/outsource/create'
    | '/package/create'
    | '/staff/create'
    | '/'
    | '/company/$companyId'
    | '/event/$eventId'
    | '/staff/$staffId'
    | '/company/$companyId/edit'
    | '/equipment/$equipmentId/edit'
    | '/event/$eventId/edit'
    | '/outsource/$outsourceId/edit'
    | '/package/$packageId/edit'
    | '/staff/$staffId/edit'
    | '/company'
    | '/event'
    | '/outsource'
    | '/staff'
  id:
    | '__root__'
    | '/_auth'
    | '/_auth/_sidebarLayout'
    | '/login/'
    | '/_auth/_sidebarLayout/equipment'
    | '/_auth/_sidebarLayout/package'
    | '/_auth/company/create'
    | '/_auth/equipment/create'
    | '/_auth/event/create'
    | '/_auth/outsource/create'
    | '/_auth/package/create'
    | '/_auth/staff/create'
    | '/_auth/_sidebarLayout/'
    | '/_auth/_sidebarLayout/company/$companyId'
    | '/_auth/_sidebarLayout/event/$eventId'
    | '/_auth/_sidebarLayout/staff/$staffId'
    | '/_auth/company/$companyId/edit'
    | '/_auth/equipment/$equipmentId/edit'
    | '/_auth/event/$eventId/edit'
    | '/_auth/outsource/$outsourceId/edit'
    | '/_auth/package/$packageId/edit'
    | '/_auth/staff/$staffId/edit'
    | '/_auth/_sidebarLayout/company/'
    | '/_auth/_sidebarLayout/event/'
    | '/_auth/_sidebarLayout/outsource/'
    | '/_auth/_sidebarLayout/staff/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  LoginIndexRoute: typeof LoginIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/_sidebarLayout': {
      id: '/_auth/_sidebarLayout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthSidebarLayoutRouteRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/_sidebarLayout/': {
      id: '/_auth/_sidebarLayout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthSidebarLayoutIndexRouteImport
      parentRoute: typeof AuthSidebarLayoutRouteRoute
    }
    '/_auth/staff/create': {
      id: '/_auth/staff/create'
      path: '/staff/create'
      fullPath: '/staff/create'
      preLoaderRoute: typeof AuthStaffCreateRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/package/create': {
      id: '/_auth/package/create'
      path: '/package/create'
      fullPath: '/package/create'
      preLoaderRoute: typeof AuthPackageCreateRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/outsource/create': {
      id: '/_auth/outsource/create'
      path: '/outsource/create'
      fullPath: '/outsource/create'
      preLoaderRoute: typeof AuthOutsourceCreateRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/event/create': {
      id: '/_auth/event/create'
      path: '/event/create'
      fullPath: '/event/create'
      preLoaderRoute: typeof AuthEventCreateRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/equipment/create': {
      id: '/_auth/equipment/create'
      path: '/equipment/create'
      fullPath: '/equipment/create'
      preLoaderRoute: typeof AuthEquipmentCreateRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/company/create': {
      id: '/_auth/company/create'
      path: '/company/create'
      fullPath: '/company/create'
      preLoaderRoute: typeof AuthCompanyCreateRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/_sidebarLayout/package': {
      id: '/_auth/_sidebarLayout/package'
      path: '/package'
      fullPath: '/package'
      preLoaderRoute: typeof AuthSidebarLayoutPackageRouteImport
      parentRoute: typeof AuthSidebarLayoutRouteRoute
    }
    '/_auth/_sidebarLayout/equipment': {
      id: '/_auth/_sidebarLayout/equipment'
      path: '/equipment'
      fullPath: '/equipment'
      preLoaderRoute: typeof AuthSidebarLayoutEquipmentRouteImport
      parentRoute: typeof AuthSidebarLayoutRouteRoute
    }
    '/_auth/_sidebarLayout/staff/': {
      id: '/_auth/_sidebarLayout/staff/'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof AuthSidebarLayoutStaffIndexRouteImport
      parentRoute: typeof AuthSidebarLayoutRouteRoute
    }
    '/_auth/_sidebarLayout/outsource/': {
      id: '/_auth/_sidebarLayout/outsource/'
      path: '/outsource'
      fullPath: '/outsource'
      preLoaderRoute: typeof AuthSidebarLayoutOutsourceIndexRouteImport
      parentRoute: typeof AuthSidebarLayoutRouteRoute
    }
    '/_auth/_sidebarLayout/event/': {
      id: '/_auth/_sidebarLayout/event/'
      path: '/event'
      fullPath: '/event'
      preLoaderRoute: typeof AuthSidebarLayoutEventIndexRouteImport
      parentRoute: typeof AuthSidebarLayoutRouteRoute
    }
    '/_auth/_sidebarLayout/company/': {
      id: '/_auth/_sidebarLayout/company/'
      path: '/company'
      fullPath: '/company'
      preLoaderRoute: typeof AuthSidebarLayoutCompanyIndexRouteImport
      parentRoute: typeof AuthSidebarLayoutRouteRoute
    }
    '/_auth/staff/$staffId/edit': {
      id: '/_auth/staff/$staffId/edit'
      path: '/staff/$staffId/edit'
      fullPath: '/staff/$staffId/edit'
      preLoaderRoute: typeof AuthStaffStaffIdEditRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/package/$packageId/edit': {
      id: '/_auth/package/$packageId/edit'
      path: '/package/$packageId/edit'
      fullPath: '/package/$packageId/edit'
      preLoaderRoute: typeof AuthPackagePackageIdEditRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/outsource/$outsourceId/edit': {
      id: '/_auth/outsource/$outsourceId/edit'
      path: '/outsource/$outsourceId/edit'
      fullPath: '/outsource/$outsourceId/edit'
      preLoaderRoute: typeof AuthOutsourceOutsourceIdEditRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/event/$eventId/edit': {
      id: '/_auth/event/$eventId/edit'
      path: '/event/$eventId/edit'
      fullPath: '/event/$eventId/edit'
      preLoaderRoute: typeof AuthEventEventIdEditRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/equipment/$equipmentId/edit': {
      id: '/_auth/equipment/$equipmentId/edit'
      path: '/equipment/$equipmentId/edit'
      fullPath: '/equipment/$equipmentId/edit'
      preLoaderRoute: typeof AuthEquipmentEquipmentIdEditRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/company/$companyId/edit': {
      id: '/_auth/company/$companyId/edit'
      path: '/company/$companyId/edit'
      fullPath: '/company/$companyId/edit'
      preLoaderRoute: typeof AuthCompanyCompanyIdEditRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/_sidebarLayout/staff/$staffId': {
      id: '/_auth/_sidebarLayout/staff/$staffId'
      path: '/staff/$staffId'
      fullPath: '/staff/$staffId'
      preLoaderRoute: typeof AuthSidebarLayoutStaffStaffIdRouteImport
      parentRoute: typeof AuthSidebarLayoutRouteRoute
    }
    '/_auth/_sidebarLayout/event/$eventId': {
      id: '/_auth/_sidebarLayout/event/$eventId'
      path: '/event/$eventId'
      fullPath: '/event/$eventId'
      preLoaderRoute: typeof AuthSidebarLayoutEventEventIdRouteImport
      parentRoute: typeof AuthSidebarLayoutRouteRoute
    }
    '/_auth/_sidebarLayout/company/$companyId': {
      id: '/_auth/_sidebarLayout/company/$companyId'
      path: '/company/$companyId'
      fullPath: '/company/$companyId'
      preLoaderRoute: typeof AuthSidebarLayoutCompanyCompanyIdRouteImport
      parentRoute: typeof AuthSidebarLayoutRouteRoute
    }
  }
}

interface AuthSidebarLayoutRouteRouteChildren {
  AuthSidebarLayoutEquipmentRoute: typeof AuthSidebarLayoutEquipmentRoute
  AuthSidebarLayoutPackageRoute: typeof AuthSidebarLayoutPackageRoute
  AuthSidebarLayoutIndexRoute: typeof AuthSidebarLayoutIndexRoute
  AuthSidebarLayoutCompanyCompanyIdRoute: typeof AuthSidebarLayoutCompanyCompanyIdRoute
  AuthSidebarLayoutEventEventIdRoute: typeof AuthSidebarLayoutEventEventIdRoute
  AuthSidebarLayoutStaffStaffIdRoute: typeof AuthSidebarLayoutStaffStaffIdRoute
  AuthSidebarLayoutCompanyIndexRoute: typeof AuthSidebarLayoutCompanyIndexRoute
  AuthSidebarLayoutEventIndexRoute: typeof AuthSidebarLayoutEventIndexRoute
  AuthSidebarLayoutOutsourceIndexRoute: typeof AuthSidebarLayoutOutsourceIndexRoute
  AuthSidebarLayoutStaffIndexRoute: typeof AuthSidebarLayoutStaffIndexRoute
}

const AuthSidebarLayoutRouteRouteChildren: AuthSidebarLayoutRouteRouteChildren =
  {
    AuthSidebarLayoutEquipmentRoute: AuthSidebarLayoutEquipmentRoute,
    AuthSidebarLayoutPackageRoute: AuthSidebarLayoutPackageRoute,
    AuthSidebarLayoutIndexRoute: AuthSidebarLayoutIndexRoute,
    AuthSidebarLayoutCompanyCompanyIdRoute:
      AuthSidebarLayoutCompanyCompanyIdRoute,
    AuthSidebarLayoutEventEventIdRoute: AuthSidebarLayoutEventEventIdRoute,
    AuthSidebarLayoutStaffStaffIdRoute: AuthSidebarLayoutStaffStaffIdRoute,
    AuthSidebarLayoutCompanyIndexRoute: AuthSidebarLayoutCompanyIndexRoute,
    AuthSidebarLayoutEventIndexRoute: AuthSidebarLayoutEventIndexRoute,
    AuthSidebarLayoutOutsourceIndexRoute: AuthSidebarLayoutOutsourceIndexRoute,
    AuthSidebarLayoutStaffIndexRoute: AuthSidebarLayoutStaffIndexRoute,
  }

const AuthSidebarLayoutRouteRouteWithChildren =
  AuthSidebarLayoutRouteRoute._addFileChildren(
    AuthSidebarLayoutRouteRouteChildren,
  )

interface AuthRouteRouteChildren {
  AuthSidebarLayoutRouteRoute: typeof AuthSidebarLayoutRouteRouteWithChildren
  AuthCompanyCreateRoute: typeof AuthCompanyCreateRoute
  AuthEquipmentCreateRoute: typeof AuthEquipmentCreateRoute
  AuthEventCreateRoute: typeof AuthEventCreateRoute
  AuthOutsourceCreateRoute: typeof AuthOutsourceCreateRoute
  AuthPackageCreateRoute: typeof AuthPackageCreateRoute
  AuthStaffCreateRoute: typeof AuthStaffCreateRoute
  AuthCompanyCompanyIdEditRoute: typeof AuthCompanyCompanyIdEditRoute
  AuthEquipmentEquipmentIdEditRoute: typeof AuthEquipmentEquipmentIdEditRoute
  AuthEventEventIdEditRoute: typeof AuthEventEventIdEditRoute
  AuthOutsourceOutsourceIdEditRoute: typeof AuthOutsourceOutsourceIdEditRoute
  AuthPackagePackageIdEditRoute: typeof AuthPackagePackageIdEditRoute
  AuthStaffStaffIdEditRoute: typeof AuthStaffStaffIdEditRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthSidebarLayoutRouteRoute: AuthSidebarLayoutRouteRouteWithChildren,
  AuthCompanyCreateRoute: AuthCompanyCreateRoute,
  AuthEquipmentCreateRoute: AuthEquipmentCreateRoute,
  AuthEventCreateRoute: AuthEventCreateRoute,
  AuthOutsourceCreateRoute: AuthOutsourceCreateRoute,
  AuthPackageCreateRoute: AuthPackageCreateRoute,
  AuthStaffCreateRoute: AuthStaffCreateRoute,
  AuthCompanyCompanyIdEditRoute: AuthCompanyCompanyIdEditRoute,
  AuthEquipmentEquipmentIdEditRoute: AuthEquipmentEquipmentIdEditRoute,
  AuthEventEventIdEditRoute: AuthEventEventIdEditRoute,
  AuthOutsourceOutsourceIdEditRoute: AuthOutsourceOutsourceIdEditRoute,
  AuthPackagePackageIdEditRoute: AuthPackagePackageIdEditRoute,
  AuthStaffStaffIdEditRoute: AuthStaffStaffIdEditRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthRouteRoute: AuthRouteRouteWithChildren,
  LoginIndexRoute: LoginIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
