/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SidebarLayoutRouteRouteImport } from './routes/_sidebarLayout/route'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as SidebarLayoutIndexRouteImport } from './routes/_sidebarLayout/index'
import { Route as StaffCreateRouteImport } from './routes/staff/create'
import { Route as PackageCreateRouteImport } from './routes/package/create'
import { Route as OutsourceCreateRouteImport } from './routes/outsource/create'
import { Route as EventCreateRouteImport } from './routes/event/create'
import { Route as EquipmentCreateRouteImport } from './routes/equipment/create'
import { Route as CompanyCreateRouteImport } from './routes/company/create'
import { Route as SidebarLayoutStaffRouteImport } from './routes/_sidebarLayout/staff'
import { Route as SidebarLayoutPackageRouteImport } from './routes/_sidebarLayout/package'
import { Route as SidebarLayoutOutsourceRouteImport } from './routes/_sidebarLayout/outsource'
import { Route as SidebarLayoutEventRouteImport } from './routes/_sidebarLayout/event'
import { Route as SidebarLayoutEquipmentRouteImport } from './routes/_sidebarLayout/equipment'
import { Route as SidebarLayoutCompanyIndexRouteImport } from './routes/_sidebarLayout/company/index'
import { Route as StaffStaffIdEditRouteImport } from './routes/staff/$staffId/edit'
import { Route as CompanyCompanyIdEditRouteImport } from './routes/company/$companyId/edit'
import { Route as SidebarLayoutCompanyCompanyIdRouteImport } from './routes/_sidebarLayout/company/$companyId'

const SidebarLayoutRouteRoute = SidebarLayoutRouteRouteImport.update({
  id: '/_sidebarLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const SidebarLayoutIndexRoute = SidebarLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SidebarLayoutRouteRoute,
} as any)
const StaffCreateRoute = StaffCreateRouteImport.update({
  id: '/staff/create',
  path: '/staff/create',
  getParentRoute: () => rootRouteImport,
} as any)
const PackageCreateRoute = PackageCreateRouteImport.update({
  id: '/package/create',
  path: '/package/create',
  getParentRoute: () => rootRouteImport,
} as any)
const OutsourceCreateRoute = OutsourceCreateRouteImport.update({
  id: '/outsource/create',
  path: '/outsource/create',
  getParentRoute: () => rootRouteImport,
} as any)
const EventCreateRoute = EventCreateRouteImport.update({
  id: '/event/create',
  path: '/event/create',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipmentCreateRoute = EquipmentCreateRouteImport.update({
  id: '/equipment/create',
  path: '/equipment/create',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyCreateRoute = CompanyCreateRouteImport.update({
  id: '/company/create',
  path: '/company/create',
  getParentRoute: () => rootRouteImport,
} as any)
const SidebarLayoutStaffRoute = SidebarLayoutStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => SidebarLayoutRouteRoute,
} as any)
const SidebarLayoutPackageRoute = SidebarLayoutPackageRouteImport.update({
  id: '/package',
  path: '/package',
  getParentRoute: () => SidebarLayoutRouteRoute,
} as any)
const SidebarLayoutOutsourceRoute = SidebarLayoutOutsourceRouteImport.update({
  id: '/outsource',
  path: '/outsource',
  getParentRoute: () => SidebarLayoutRouteRoute,
} as any)
const SidebarLayoutEventRoute = SidebarLayoutEventRouteImport.update({
  id: '/event',
  path: '/event',
  getParentRoute: () => SidebarLayoutRouteRoute,
} as any)
const SidebarLayoutEquipmentRoute = SidebarLayoutEquipmentRouteImport.update({
  id: '/equipment',
  path: '/equipment',
  getParentRoute: () => SidebarLayoutRouteRoute,
} as any)
const SidebarLayoutCompanyIndexRoute =
  SidebarLayoutCompanyIndexRouteImport.update({
    id: '/company/',
    path: '/company/',
    getParentRoute: () => SidebarLayoutRouteRoute,
  } as any)
const StaffStaffIdEditRoute = StaffStaffIdEditRouteImport.update({
  id: '/staff/$staffId/edit',
  path: '/staff/$staffId/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyCompanyIdEditRoute = CompanyCompanyIdEditRouteImport.update({
  id: '/company/$companyId/edit',
  path: '/company/$companyId/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const SidebarLayoutCompanyCompanyIdRoute =
  SidebarLayoutCompanyCompanyIdRouteImport.update({
    id: '/company/$companyId',
    path: '/company/$companyId',
    getParentRoute: () => SidebarLayoutRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/equipment': typeof SidebarLayoutEquipmentRoute
  '/event': typeof SidebarLayoutEventRoute
  '/outsource': typeof SidebarLayoutOutsourceRoute
  '/package': typeof SidebarLayoutPackageRoute
  '/staff': typeof SidebarLayoutStaffRoute
  '/company/create': typeof CompanyCreateRoute
  '/equipment/create': typeof EquipmentCreateRoute
  '/event/create': typeof EventCreateRoute
  '/outsource/create': typeof OutsourceCreateRoute
  '/package/create': typeof PackageCreateRoute
  '/staff/create': typeof StaffCreateRoute
  '/': typeof SidebarLayoutIndexRoute
  '/login': typeof LoginIndexRoute
  '/company/$companyId': typeof SidebarLayoutCompanyCompanyIdRoute
  '/company/$companyId/edit': typeof CompanyCompanyIdEditRoute
  '/staff/$staffId/edit': typeof StaffStaffIdEditRoute
  '/company': typeof SidebarLayoutCompanyIndexRoute
}
export interface FileRoutesByTo {
  '/equipment': typeof SidebarLayoutEquipmentRoute
  '/event': typeof SidebarLayoutEventRoute
  '/outsource': typeof SidebarLayoutOutsourceRoute
  '/package': typeof SidebarLayoutPackageRoute
  '/staff': typeof SidebarLayoutStaffRoute
  '/company/create': typeof CompanyCreateRoute
  '/equipment/create': typeof EquipmentCreateRoute
  '/event/create': typeof EventCreateRoute
  '/outsource/create': typeof OutsourceCreateRoute
  '/package/create': typeof PackageCreateRoute
  '/staff/create': typeof StaffCreateRoute
  '/': typeof SidebarLayoutIndexRoute
  '/login': typeof LoginIndexRoute
  '/company/$companyId': typeof SidebarLayoutCompanyCompanyIdRoute
  '/company/$companyId/edit': typeof CompanyCompanyIdEditRoute
  '/staff/$staffId/edit': typeof StaffStaffIdEditRoute
  '/company': typeof SidebarLayoutCompanyIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_sidebarLayout': typeof SidebarLayoutRouteRouteWithChildren
  '/_sidebarLayout/equipment': typeof SidebarLayoutEquipmentRoute
  '/_sidebarLayout/event': typeof SidebarLayoutEventRoute
  '/_sidebarLayout/outsource': typeof SidebarLayoutOutsourceRoute
  '/_sidebarLayout/package': typeof SidebarLayoutPackageRoute
  '/_sidebarLayout/staff': typeof SidebarLayoutStaffRoute
  '/company/create': typeof CompanyCreateRoute
  '/equipment/create': typeof EquipmentCreateRoute
  '/event/create': typeof EventCreateRoute
  '/outsource/create': typeof OutsourceCreateRoute
  '/package/create': typeof PackageCreateRoute
  '/staff/create': typeof StaffCreateRoute
  '/_sidebarLayout/': typeof SidebarLayoutIndexRoute
  '/login/': typeof LoginIndexRoute
  '/_sidebarLayout/company/$companyId': typeof SidebarLayoutCompanyCompanyIdRoute
  '/company/$companyId/edit': typeof CompanyCompanyIdEditRoute
  '/staff/$staffId/edit': typeof StaffStaffIdEditRoute
  '/_sidebarLayout/company/': typeof SidebarLayoutCompanyIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/equipment'
    | '/event'
    | '/outsource'
    | '/package'
    | '/staff'
    | '/company/create'
    | '/equipment/create'
    | '/event/create'
    | '/outsource/create'
    | '/package/create'
    | '/staff/create'
    | '/'
    | '/login'
    | '/company/$companyId'
    | '/company/$companyId/edit'
    | '/staff/$staffId/edit'
    | '/company'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/equipment'
    | '/event'
    | '/outsource'
    | '/package'
    | '/staff'
    | '/company/create'
    | '/equipment/create'
    | '/event/create'
    | '/outsource/create'
    | '/package/create'
    | '/staff/create'
    | '/'
    | '/login'
    | '/company/$companyId'
    | '/company/$companyId/edit'
    | '/staff/$staffId/edit'
    | '/company'
  id:
    | '__root__'
    | '/_sidebarLayout'
    | '/_sidebarLayout/equipment'
    | '/_sidebarLayout/event'
    | '/_sidebarLayout/outsource'
    | '/_sidebarLayout/package'
    | '/_sidebarLayout/staff'
    | '/company/create'
    | '/equipment/create'
    | '/event/create'
    | '/outsource/create'
    | '/package/create'
    | '/staff/create'
    | '/_sidebarLayout/'
    | '/login/'
    | '/_sidebarLayout/company/$companyId'
    | '/company/$companyId/edit'
    | '/staff/$staffId/edit'
    | '/_sidebarLayout/company/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SidebarLayoutRouteRoute: typeof SidebarLayoutRouteRouteWithChildren
  CompanyCreateRoute: typeof CompanyCreateRoute
  EquipmentCreateRoute: typeof EquipmentCreateRoute
  EventCreateRoute: typeof EventCreateRoute
  OutsourceCreateRoute: typeof OutsourceCreateRoute
  PackageCreateRoute: typeof PackageCreateRoute
  StaffCreateRoute: typeof StaffCreateRoute
  LoginIndexRoute: typeof LoginIndexRoute
  CompanyCompanyIdEditRoute: typeof CompanyCompanyIdEditRoute
  StaffStaffIdEditRoute: typeof StaffStaffIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_sidebarLayout': {
      id: '/_sidebarLayout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof SidebarLayoutRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_sidebarLayout/': {
      id: '/_sidebarLayout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof SidebarLayoutIndexRouteImport
      parentRoute: typeof SidebarLayoutRouteRoute
    }
    '/staff/create': {
      id: '/staff/create'
      path: '/staff/create'
      fullPath: '/staff/create'
      preLoaderRoute: typeof StaffCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/package/create': {
      id: '/package/create'
      path: '/package/create'
      fullPath: '/package/create'
      preLoaderRoute: typeof PackageCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/outsource/create': {
      id: '/outsource/create'
      path: '/outsource/create'
      fullPath: '/outsource/create'
      preLoaderRoute: typeof OutsourceCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/event/create': {
      id: '/event/create'
      path: '/event/create'
      fullPath: '/event/create'
      preLoaderRoute: typeof EventCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipment/create': {
      id: '/equipment/create'
      path: '/equipment/create'
      fullPath: '/equipment/create'
      preLoaderRoute: typeof EquipmentCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company/create': {
      id: '/company/create'
      path: '/company/create'
      fullPath: '/company/create'
      preLoaderRoute: typeof CompanyCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_sidebarLayout/staff': {
      id: '/_sidebarLayout/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof SidebarLayoutStaffRouteImport
      parentRoute: typeof SidebarLayoutRouteRoute
    }
    '/_sidebarLayout/package': {
      id: '/_sidebarLayout/package'
      path: '/package'
      fullPath: '/package'
      preLoaderRoute: typeof SidebarLayoutPackageRouteImport
      parentRoute: typeof SidebarLayoutRouteRoute
    }
    '/_sidebarLayout/outsource': {
      id: '/_sidebarLayout/outsource'
      path: '/outsource'
      fullPath: '/outsource'
      preLoaderRoute: typeof SidebarLayoutOutsourceRouteImport
      parentRoute: typeof SidebarLayoutRouteRoute
    }
    '/_sidebarLayout/event': {
      id: '/_sidebarLayout/event'
      path: '/event'
      fullPath: '/event'
      preLoaderRoute: typeof SidebarLayoutEventRouteImport
      parentRoute: typeof SidebarLayoutRouteRoute
    }
    '/_sidebarLayout/equipment': {
      id: '/_sidebarLayout/equipment'
      path: '/equipment'
      fullPath: '/equipment'
      preLoaderRoute: typeof SidebarLayoutEquipmentRouteImport
      parentRoute: typeof SidebarLayoutRouteRoute
    }
    '/_sidebarLayout/company/': {
      id: '/_sidebarLayout/company/'
      path: '/company'
      fullPath: '/company'
      preLoaderRoute: typeof SidebarLayoutCompanyIndexRouteImport
      parentRoute: typeof SidebarLayoutRouteRoute
    }
    '/staff/$staffId/edit': {
      id: '/staff/$staffId/edit'
      path: '/staff/$staffId/edit'
      fullPath: '/staff/$staffId/edit'
      preLoaderRoute: typeof StaffStaffIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company/$companyId/edit': {
      id: '/company/$companyId/edit'
      path: '/company/$companyId/edit'
      fullPath: '/company/$companyId/edit'
      preLoaderRoute: typeof CompanyCompanyIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_sidebarLayout/company/$companyId': {
      id: '/_sidebarLayout/company/$companyId'
      path: '/company/$companyId'
      fullPath: '/company/$companyId'
      preLoaderRoute: typeof SidebarLayoutCompanyCompanyIdRouteImport
      parentRoute: typeof SidebarLayoutRouteRoute
    }
  }
}

interface SidebarLayoutRouteRouteChildren {
  SidebarLayoutEquipmentRoute: typeof SidebarLayoutEquipmentRoute
  SidebarLayoutEventRoute: typeof SidebarLayoutEventRoute
  SidebarLayoutOutsourceRoute: typeof SidebarLayoutOutsourceRoute
  SidebarLayoutPackageRoute: typeof SidebarLayoutPackageRoute
  SidebarLayoutStaffRoute: typeof SidebarLayoutStaffRoute
  SidebarLayoutIndexRoute: typeof SidebarLayoutIndexRoute
  SidebarLayoutCompanyCompanyIdRoute: typeof SidebarLayoutCompanyCompanyIdRoute
  SidebarLayoutCompanyIndexRoute: typeof SidebarLayoutCompanyIndexRoute
}

const SidebarLayoutRouteRouteChildren: SidebarLayoutRouteRouteChildren = {
  SidebarLayoutEquipmentRoute: SidebarLayoutEquipmentRoute,
  SidebarLayoutEventRoute: SidebarLayoutEventRoute,
  SidebarLayoutOutsourceRoute: SidebarLayoutOutsourceRoute,
  SidebarLayoutPackageRoute: SidebarLayoutPackageRoute,
  SidebarLayoutStaffRoute: SidebarLayoutStaffRoute,
  SidebarLayoutIndexRoute: SidebarLayoutIndexRoute,
  SidebarLayoutCompanyCompanyIdRoute: SidebarLayoutCompanyCompanyIdRoute,
  SidebarLayoutCompanyIndexRoute: SidebarLayoutCompanyIndexRoute,
}

const SidebarLayoutRouteRouteWithChildren =
  SidebarLayoutRouteRoute._addFileChildren(SidebarLayoutRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  SidebarLayoutRouteRoute: SidebarLayoutRouteRouteWithChildren,
  CompanyCreateRoute: CompanyCreateRoute,
  EquipmentCreateRoute: EquipmentCreateRoute,
  EventCreateRoute: EventCreateRoute,
  OutsourceCreateRoute: OutsourceCreateRoute,
  PackageCreateRoute: PackageCreateRoute,
  StaffCreateRoute: StaffCreateRoute,
  LoginIndexRoute: LoginIndexRoute,
  CompanyCompanyIdEditRoute: CompanyCompanyIdEditRoute,
  StaffStaffIdEditRoute: StaffStaffIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
